CREATE SCHEMA identity AUTHORIZATION identity;
CREATE SCHEMA travel AUTHORIZATION travel;
CREATE SCHEMA payments AUTHORIZATION payments;
SET ROLE identity;
CREATE TABLE identity.users(id uuid PRIMARY KEY, name varchar(100) NOT NULL, email varchar(254) UNIQUE NOT NULL, role text NOT NULL CHECK(role IN ('ADMIN','TRAVEL_MANAGER','VIEWER')),status text NOT NULL CHECK(status IN ('ACTIVE','SUSPENDED')),password_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE identity.sessions(token_hash text PRIMARY KEY,user_id uuid NOT NULL REFERENCES identity.users ON DELETE CASCADE,csrf text NOT NULL,expires_at timestamptz NOT NULL);
CREATE INDEX ON identity.sessions(user_id);
CREATE TABLE identity.login_attempts(email text PRIMARY KEY,failures int NOT NULL DEFAULT 0,locked_until timestamptz);
CREATE TABLE identity.bootstrap_state(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),initialized_at timestamptz NOT NULL DEFAULT now());
GRANT USAGE ON SCHEMA identity TO travel,payments;
GRANT REFERENCES(id) ON identity.users TO travel,payments;
RESET ROLE;
SET ROLE payments;
CREATE TABLE payments.gateways(id uuid PRIMARY KEY,name varchar(100) NOT NULL,provider text NOT NULL CHECK(provider IN ('STRIPE','PAYPAL')),currency char(3) NOT NULL,enabled boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
GRANT USAGE ON SCHEMA payments TO travel;
GRANT REFERENCES(id) ON payments.gateways TO travel;
RESET ROLE;
SET ROLE travel;
CREATE TABLE travel.travels(id uuid PRIMARY KEY,title varchar(150) NOT NULL,start_date date NOT NULL,end_date date NOT NULL CHECK(end_date>=start_date),status text NOT NULL CHECK(status IN ('DRAFT','PUBLISHED','ARCHIVED')),price numeric(12,2) NOT NULL CHECK(price>=0),capacity int NOT NULL CHECK(capacity>0),description text,image text NOT NULL,version int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE travel.stops(travel_id uuid NOT NULL REFERENCES travel.travels ON DELETE CASCADE,position int NOT NULL,destination text NOT NULL,country text NOT NULL,activities text NOT NULL,accommodation text NOT NULL,transportation text NOT NULL,PRIMARY KEY(travel_id,position));
CREATE TABLE travel.participants(travel_id uuid NOT NULL REFERENCES travel.travels ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES identity.users ON DELETE CASCADE,PRIMARY KEY(travel_id,user_id));
CREATE INDEX ON travel.participants(user_id);
CREATE TABLE travel.graph_outbox(id bigserial PRIMARY KEY,travel_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
GRANT USAGE ON SCHEMA travel TO payments;
GRANT REFERENCES(id) ON travel.travels TO payments;
RESET ROLE;
SET ROLE payments;
CREATE TABLE payments.transactions(id uuid PRIMARY KEY,user_id uuid REFERENCES identity.users ON DELETE SET NULL,travel_id uuid REFERENCES travel.travels ON DELETE SET NULL,gateway_id uuid REFERENCES payments.gateways ON DELETE SET NULL,provider_reference text UNIQUE,amount numeric(12,2) NOT NULL,currency char(3) NOT NULL,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
RESET ROLE;
