apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  namespace: travel-plan
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity
  namespace: travel-plan
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: travel
  namespace: travel-plan
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: travel-plan
automountServiceAccountToken: false
